      - layout: top-middle
        title: Pruebas de aplicaciones web
        link: github.com/gopi9204
        additional_links:
          - title: Ver repositorio
            icon: fab fa-github
            url: https://github.com/gopi9204
        quote: >
          Validación funcional y visual del módulo “Compartir automóvil”.
        description: |
          Diseñé listas de comprobación y casos de prueba en distintos navegadores, documentando defectos con evidencia reproducible y criterios de severidad, mejorando la estabilidad del flujo de usuario.

          <div class="project-gallery">
            <img src="images/Proyecto0301.png" alt="Prueba aplicaciones web 1">
            <img src="images/Proyecto0302.png" alt="Prueba aplicaciones web 2">
            <img src="images/Proyecto0303.png" alt="Prueba aplicaciones web 3">
          </div>

      - layout: top-middle
        title: Documentación de pruebas
        link: github.com/gopi9204
        additional_links:
          - title: Ver repositorio
            icon: fab fa-github
            url: https://github.com/gopi9204
        quote: >
          Diseño estructurado de documentación QA.
        description: |
          Analicé requisitos y apliqué técnicas de diseño de pruebas con clases de equivalencia y valores límite, asegurando cobertura funcional y validación de entradas en el flujo de registro de licencias.

          <div class="project-gallery">
            <img src="images/Proyecto0201.png" alt="Documentación pruebas 1">
            <img src="images/Proyecto0202.png" alt="Documentación pruebas 2">
          </div>

      - layout: top-middle
        title: Pruebas de regresión - Urban Routes
        link: github.com/gopi9204
        additional_links:
          - title: Ver repositorio
            icon: fab fa-github
            url: https://github.com/gopi9204
        quote: >
          Ejecución de pruebas de regresión sobre aplicación de transporte.
        description: |
          Verifiqué cálculo de rutas, duración y tarifas tras actualizaciones, identificando errores en interfaz y lógica de negocio, fortaleciendo la trazabilidad y la consistencia de reportes QA.

          <div class="project-gallery">
            <img src="images/Proyecto0101.png" alt="Prueba regresión 1">
            <img src="images/Proyecto0102.png" alt="Prueba regresión 2">
          </div>
